import { AppContainer } from "./AppContainer.js";
import { Router } from "./Router.js";
import { hydrateIcons } from "../DesignSystem/icons.js";
import { money,parseAmount } from "../Core/Formatting/formatters.js";
import { DashboardView } from "../Features/Dashboard/DashboardView.js";
import { TransactionsView } from "../Features/Transactions/TransactionsView.js";
import { AccountsView } from "../Features/Accounts/AccountsView.js";
import { SavingsView } from "../Features/Savings/SavingsView.js";
import { UpcomingView } from "../Features/Upcoming/UpcomingView.js";
import { ReportsView } from "../Features/Reports/ReportsView.js";
import { SettingsView } from "../Features/Settings/SettingsView.js";

const container=new AppContainer(),content=document.querySelector("#app-content"),shell=document.querySelector("#app-shell"),authScreen=document.querySelector("#auth-screen"),mobileFab=document.querySelector(".mobile-fab"),loading=document.querySelector("#app-loading");
const forms={transaction:document.querySelector("#transaction-form"),account:document.querySelector("#account-form"),scheduled:document.querySelector("#scheduled-form"),category:document.querySelector("#category-form"),assetType:document.querySelector("#asset-type-form"),instrument:document.querySelector("#instrument-form"),lot:document.querySelector("#lot-form"),sale:document.querySelector("#sale-form"),price:document.querySelector("#price-form")};
const dialogs=Object.fromEntries(Object.entries(forms).map(([key,form])=>[key,form.closest("dialog")]));
const views={dashboard:DashboardView,transactions:TransactionsView,accounts:AccountsView,savings:SavingsView,upcoming:UpcomingView,reports:ReportsView,settings:SettingsView};
const titles={dashboard:["Canlı finans görünümü","Ana Sayfa"],transactions:["Tüm finansal hareketler","İşlemler"],accounts:["Bakiye ve limit yönetimi","Hesaplar"],savings:["Portföy, maliyet ve getiri","Birikimler"],upcoming:["Ödeme ve tahsilat planı","Yaklaşan"],reports:["Canlı finansal sonuçlar","Raporlar"],settings:["Kategoriler ve birikim tanımları","Ayarlar"]};
const transactionFilters={search:"",kind:"",from:"",to:"",accountIds:[],knownAccountIds:[],accountsInitialized:false};
let currentRoute="dashboard",ready=false,busy=false,apiStatus={online:false,reason:"Bağlantı denetleniyor"};
const snapshot=()=>container.finance.snapshot();

function showAuth(){ready=false;shell.hidden=true;mobileFab.hidden=true;authScreen.hidden=false;document.querySelector("#auth-error").textContent="";}
function showApp(){authScreen.hidden=true;shell.hidden=false;mobileFab.hidden=false;const state=snapshot(),name=state.user?.displayName||state.user?.email||"DefterX";document.querySelector("#active-book-name").textContent=state.book?.name||"Defter";document.querySelector("#profile-name").textContent=name;document.querySelector("#profile-email").textContent=state.user?.email||"Canlı kullanıcı";document.querySelector("#profile-avatar").textContent=name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toLocaleUpperCase("tr-TR");}
function setBusy(value){busy=value;loading.hidden=!value;document.querySelector("#sync-button")?.classList.toggle("spinning",value);}

function render(route=currentRoute){
  currentRoute=route;if(!ready)return;
  if(route==="transactions")syncTransactionAccountFilter();
  const [eyebrow,title]=titles[route]||titles.dashboard;document.querySelector("#page-eyebrow").textContent=eyebrow;document.querySelector("#page-title").textContent=title;
  document.querySelectorAll("[data-route]").forEach(item=>item.classList.toggle("active",item.dataset.route===route));
  content.innerHTML=views[route](snapshot(),{apiStatus,configuration:container.configuration,transactionFilters});
  bindViewEvents();content.focus({preventScroll:true});
}

async function bootstrap(){
  setBusy(true);apiStatus=await container.apiClient.health();
  if(!container.apiClient.hasSession()){setBusy(false);showAuth();return;}
  try{await container.finance.initialize();ready=true;showApp();render(currentRoute);}
  catch(error){if(error.status===401||error.message==="AUTH_REQUIRED")showAuth();else{showAuth();document.querySelector("#auth-error").textContent=errorMessage(error);}}
  finally{setBusy(false);}
}

async function mutate(action,success,route=currentRoute){
  if(busy)return;setBusy(true);
  try{await action();await new Promise(resolve=>setTimeout(resolve,250));await container.finance.refresh();if(route==="transactions")await container.finance.loadTransactions(transactionFilters);toast(success,true);render(route);return true;}
  catch(error){toast(errorMessage(error));return false;}
  finally{setBusy(false);}
}

function bindViewEvents(){
  const search=document.querySelector("#transaction-search"),kind=document.querySelector("#transaction-kind-filter"),from=document.querySelector("#transaction-from"),to=document.querySelector("#transaction-to");
  search?.addEventListener("input",()=>{transactionFilters.search=search.value;applyTransactionFilters();});kind?.addEventListener("change",()=>{transactionFilters.kind=kind.value;applyTransactionFilters();});from?.addEventListener("change",()=>{transactionFilters.from=from.value;loadTransactionLedger();});to?.addEventListener("change",()=>{transactionFilters.to=to.value;loadTransactionLedger();});
  document.querySelector("[data-transaction-account-all]")?.addEventListener("change",event=>{transactionFilters.accountIds=event.currentTarget.checked?[...transactionFilters.knownAccountIds]:[];loadTransactionLedger();});
  document.querySelectorAll("[data-transaction-account]").forEach(x=>x.addEventListener("change",()=>{const ids=new Set(transactionFilters.accountIds);x.checked?ids.add(x.dataset.transactionAccount):ids.delete(x.dataset.transactionAccount);transactionFilters.accountIds=[...ids];loadTransactionLedger();}));
  document.querySelector("#clear-transaction-filters")?.addEventListener("click",()=>{Object.assign(transactionFilters,{search:"",kind:"",from:"",to:"",accountIds:[...transactionFilters.knownAccountIds]});loadTransactionLedger();});document.querySelector("#export-transactions")?.addEventListener("click",exportVisibleTransactions);
  document.querySelectorAll("[data-edit-transaction]").forEach(x=>x.addEventListener("click",()=>openTransaction(x.dataset.editTransaction)));document.querySelectorAll("[data-delete-transaction]").forEach(x=>x.addEventListener("click",()=>deleteTransaction(x.dataset.deleteTransaction)));
  document.querySelector("#open-account-dialog")?.addEventListener("click",()=>openAccount());document.querySelectorAll("[data-edit-account]").forEach(x=>x.addEventListener("click",()=>openAccount(x.dataset.editAccount)));document.querySelectorAll("[data-delete-account]").forEach(x=>x.addEventListener("click",()=>deleteAccount(x.dataset.deleteAccount)));
  document.querySelector("#open-scheduled-dialog")?.addEventListener("click",()=>openScheduled());document.querySelectorAll("[data-edit-scheduled]").forEach(x=>x.addEventListener("click",()=>openScheduled(x.dataset.editScheduled)));document.querySelectorAll("[data-delete-scheduled]").forEach(x=>x.addEventListener("click",()=>deleteScheduled(x.dataset.deleteScheduled)));
  document.querySelectorAll("[data-realize-scheduled]").forEach(x=>x.addEventListener("click",()=>realizeScheduled(x.dataset.realizeScheduled)));
  document.querySelectorAll("[data-upcoming-filter]").forEach(x=>x.addEventListener("click",()=>{snapshot().upcomingFilter=x.dataset.upcomingFilter;render("upcoming");}));
  document.querySelectorAll("[data-cashflow-range]").forEach(x=>x.addEventListener("click",()=>loadCashflowRange(x.dataset.cashflowRange)));
  document.querySelectorAll("[data-cashflow-series]").forEach(x=>x.addEventListener("change",()=>{snapshot().cashflowVisible[x.dataset.cashflowSeries]=x.checked;render("dashboard");}));
  document.querySelector("[data-cashflow-account-all]")?.addEventListener("change",event=>loadCashflowAccounts(event.currentTarget.checked?snapshot().accounts.filter(x=>!x.isArchived).map(x=>x.id):[]));
  document.querySelectorAll("[data-cashflow-account]").forEach(x=>x.addEventListener("change",()=>{const ids=new Set(snapshot().cashflowAccountIds);x.checked?ids.add(x.dataset.cashflowAccount):ids.delete(x.dataset.cashflowAccount);loadCashflowAccounts([...ids]);}));
  document.querySelector("#open-category-dialog")?.addEventListener("click",()=>openCategory());document.querySelectorAll("[data-edit-category]").forEach(x=>x.addEventListener("click",()=>openCategory(x.dataset.editCategory)));document.querySelectorAll("[data-delete-category]").forEach(x=>x.addEventListener("click",()=>deleteCategory(x.dataset.deleteCategory)));document.querySelectorAll("[data-activate-category]").forEach(x=>x.addEventListener("click",()=>activateCategory(x.dataset.activateCategory)));
  document.querySelector("#open-asset-type-dialog")?.addEventListener("click",()=>openAssetType());document.querySelectorAll("[data-edit-asset-type]").forEach(x=>x.addEventListener("click",()=>openAssetType(x.dataset.editAssetType)));document.querySelectorAll("[data-delete-asset-type]").forEach(x=>x.addEventListener("click",()=>deleteAssetType(x.dataset.deleteAssetType)));document.querySelectorAll("[data-activate-asset-type]").forEach(x=>x.addEventListener("click",()=>activateAssetType(x.dataset.activateAssetType)));
  document.querySelector("#open-instrument-dialog")?.addEventListener("click",()=>openInstrument());document.querySelectorAll("[data-edit-instrument]").forEach(x=>x.addEventListener("click",()=>openInstrument(x.dataset.editInstrument)));document.querySelectorAll("[data-delete-instrument]").forEach(x=>x.addEventListener("click",()=>deleteInstrument(x.dataset.deleteInstrument)));document.querySelectorAll("[data-price-instrument]").forEach(x=>x.addEventListener("click",()=>openPrice(x.dataset.priceInstrument)));
  document.querySelector("#open-lot-dialog")?.addEventListener("click",()=>openLot());document.querySelectorAll("[data-edit-lot]").forEach(x=>x.addEventListener("click",()=>openLot(x.dataset.editLot)));document.querySelectorAll("[data-delete-lot]").forEach(x=>x.addEventListener("click",()=>deleteLot(x.dataset.deleteLot)));document.querySelector("#open-sale-dialog")?.addEventListener("click",()=>openSale());document.querySelectorAll("[data-edit-sale]").forEach(x=>x.addEventListener("click",()=>openSale(x.dataset.editSale)));document.querySelectorAll("[data-delete-sale]").forEach(x=>x.addEventListener("click",()=>deleteSale(x.dataset.deleteSale)));
  document.querySelector("#logout-button")?.addEventListener("click",logout);applyTransactionFilters();bindCashflowHover();
}

function syncTransactionAccountFilter(){const ids=snapshot().accounts.map(item=>item.id),known=transactionFilters.knownAccountIds,allWereSelected=!transactionFilters.accountsInitialized||(known.length===transactionFilters.accountIds.length&&known.every(id=>transactionFilters.accountIds.includes(id)));transactionFilters.accountIds=allWereSelected?ids:transactionFilters.accountIds.filter(id=>ids.includes(id));transactionFilters.knownAccountIds=ids;transactionFilters.accountsInitialized=true;}
function applyTransactionFilters(){const query=transactionFilters.search.toLocaleLowerCase("tr-TR").trim();let count=0;document.querySelectorAll("#all-transactions .table-row[data-transaction-id]").forEach(row=>{row.hidden=Boolean((query&&!row.dataset.search.includes(query))||(transactionFilters.kind&&row.dataset.kind!==transactionFilters.kind));if(!row.hidden)count++;});const label=document.querySelector("#transaction-result-count");if(label)label.textContent=`${count} kayıt bulundu`;const empty=document.querySelector("#transaction-empty");if(empty)empty.hidden=count!==0;}
async function loadTransactionLedger(){if(busy)return;setBusy(true);try{await container.finance.loadTransactions(transactionFilters);render("transactions");}catch(error){toast(errorMessage(error));render("transactions");}finally{setBusy(false);}}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;}
function isoAtNoon(value){return new Date(`${value}T12:00:00`).toISOString();}
function decimal(value){const number=parseAmount(value);return number>0?String(number):null;}
function options(items,label,empty="Seçin"){return `<option value="">${empty}</option>${items.map(item=>`<option value="${item.id}">${label(item)}</option>`).join("")}`;}

function fillTransactionOptions(){const state=snapshot(),kind=forms.transaction.elements.kind.value;forms.transaction.elements.accountId.innerHTML=options(state.accounts.filter(x=>!x.isArchived),x=>x.name,"Hesap seçin");forms.transaction.elements.targetAccountId.innerHTML=options(state.accounts.filter(x=>!x.isArchived),x=>x.name,"Hedef hesap seçin");forms.transaction.elements.categoryId.innerHTML=options(state.categories.filter(x=>x.isActive&&x.kind===kind),x=>x.name,"Kategori seçin");updateTransactionFields();}
function updateTransactionFields(){const transfer=forms.transaction.elements.kind.value==="transfer",target=forms.transaction.elements.targetAccountId,category=forms.transaction.elements.categoryId;document.querySelector("#target-account-field").hidden=!transfer;document.querySelector("#category-field").hidden=transfer;document.querySelector("#transaction-account-caption").textContent=transfer?"Kaynak hesap":"Hesap";target.required=transfer;target.disabled=!transfer;category.required=!transfer;category.disabled=transfer;if(!transfer)target.value="";}
function openTransaction(id=""){const item=snapshot().transactions.find(x=>x.id===id);forms.transaction.reset();forms.transaction.elements.transactionId.value=id;forms.transaction.elements.date.value=item?.date||today();if(item&&["income","expense","transfer"].includes(item.kind))forms.transaction.elements.kind.value=item.kind;fillTransactionOptions();if(item){forms.transaction.elements.amount.value=String(item.amount).replace(".",",");forms.transaction.elements.description.value=item.description;forms.transaction.elements.accountId.value=item.accountId||"";forms.transaction.elements.targetAccountId.value=item.targetAccountId||"";forms.transaction.elements.categoryId.value=item.categoryId||"";}dialogs.transaction.querySelector("h2").textContent=item?"İşlemi düzelt":"Yeni işlem";dialogs.transaction.showModal();}
async function deleteTransaction(id){const item=snapshot().transactions.find(x=>x.id===id);if(!item||!confirm(`“${item.description}” işlemi iptal edilsin mi?`))return;await mutate(()=>container.finance.deleteTransaction(id),"İşlem ters kayıtla iptal edildi","transactions");}

function openAccount(id=""){const item=snapshot().accounts.find(x=>x.id===id);forms.account.reset();forms.account.elements.accountId.value=id;forms.account.elements.version.value=item?.version||"";forms.account.elements.openingBalance.value="0";forms.account.elements.accountType.disabled=false;document.querySelector(".opening-field").hidden=Boolean(item);if(item){forms.account.elements.name.value=item.name;forms.account.elements.accountType.value=item.accountType;forms.account.elements.allowNegativeBalance.checked=item.allowNegativeBalance;forms.account.elements.creditLimit.value=item.creditLimit||"";}updateAccountLimit();dialogs.account.querySelector("h2").textContent=item?"Hesabı düzenle":"Hesap ekle";dialogs.account.showModal();}
function updateAccountLimit(){const allowed=forms.account.elements.allowNegativeBalance.checked;document.querySelector("#credit-limit-field").hidden=!allowed;}
async function deleteAccount(id){const item=snapshot().accounts.find(x=>x.id===id);if(!item||item.isArchived||!confirm(`“${item.name}” hesabı silinsin mi? Kullanılmışsa arşivlenecektir.`))return;await mutate(()=>container.finance.deleteAccount(id,item.version),"Hesap silindi veya geçmişi olduğu için arşivlendi","accounts");}

function fillScheduledOptions(kind){const state=snapshot(),transfer=kind==="transfer",target=forms.scheduled.elements.targetAccountId,category=forms.scheduled.elements.categoryId;forms.scheduled.elements.accountId.innerHTML=options(state.accounts.filter(x=>!x.isArchived),x=>x.name,"Hesap seçin");target.innerHTML=options(state.accounts.filter(x=>!x.isArchived),x=>x.name,"Hedef seçin");category.innerHTML=options(state.categories.filter(x=>x.isActive&&x.kind===kind),x=>x.name,"Kategori seçin");document.querySelector(".scheduled-target").hidden=!transfer;document.querySelector(".scheduled-category").hidden=transfer;document.querySelector("#scheduled-account-caption").textContent=transfer?"Kaynak hesap":"Hesap";target.required=transfer;target.disabled=!transfer;category.required=!transfer;category.disabled=transfer;if(!transfer)target.value="";}
function updateScheduledRepeat(){const repeating=forms.scheduled.elements.repeat.value!=="NONE",field=document.querySelector(".scheduled-repeat-until");field.hidden=!repeating;forms.scheduled.elements.repeatUntil.required=repeating;forms.scheduled.elements.repeatUntil.min=forms.scheduled.elements.date.value;if(repeating&&!forms.scheduled.elements.repeatUntil.value)forms.scheduled.elements.repeatUntil.value=forms.scheduled.elements.date.value;}
function openScheduled(id=""){const item=snapshot().upcoming.find(x=>x.id===id);forms.scheduled.reset();forms.scheduled.elements.scheduledId.value=id;forms.scheduled.elements.version.value=item?.version||"";forms.scheduled.elements.date.value=item?.date||today();if(item)forms.scheduled.elements.kind.value=item.kind;fillScheduledOptions(forms.scheduled.elements.kind.value);document.querySelector(".scheduled-repeat").hidden=Boolean(item);document.querySelector(".scheduled-repeat-until").hidden=true;forms.scheduled.elements.repeat.disabled=Boolean(item);forms.scheduled.elements.repeatUntil.disabled=Boolean(item);if(item){forms.scheduled.elements.title.value=item.title;forms.scheduled.elements.amount.value=String(item.amount).replace(".",",");forms.scheduled.elements.accountId.value=item.accountId;forms.scheduled.elements.targetAccountId.value=item.targetAccountId||"";forms.scheduled.elements.categoryId.value=item.categoryId||"";}else{forms.scheduled.elements.repeat.disabled=false;forms.scheduled.elements.repeatUntil.disabled=false;updateScheduledRepeat();}dialogs.scheduled.querySelector("h2").textContent=item?"Planı düzenle":"Planlı işlem";dialogs.scheduled.showModal();}
async function deleteScheduled(id){const item=snapshot().upcoming.find(x=>x.id===id);if(!item||!confirm(`“${item.title}” planı silinsin mi?`))return;await mutate(()=>container.finance.deleteScheduled(id,item.version),"Planlı işlem silindi","upcoming");}
async function realizeScheduled(id){const item=snapshot().upcoming.find(x=>x.id===id);if(!item||!confirm(`“${item.title}” gerçekleşti olarak işlemlere aktarılsın mı?`))return;await mutate(()=>container.finance.realizeScheduled(id,item.version),"Planlı kayıt işlemlere aktarıldı","upcoming");}
async function loadCashflowRange(range){if(busy||range===snapshot().cashflowRange)return;setBusy(true);try{await container.finance.loadCashflow(range);render("dashboard");}catch(error){toast(errorMessage(error),true);}finally{setBusy(false);}}
async function loadCashflowAccounts(accountIds){if(busy)return;setBusy(true);try{await container.finance.loadCashflowAccounts(accountIds);render("dashboard");}catch(error){toast(errorMessage(error));render("dashboard");}finally{setBusy(false);}}
function bindCashflowHover(){
  const visual=document.querySelector(".cashflow-visual"),tooltip=document.querySelector("#cashflow-tooltip");if(!visual||!tooltip)return;
  const hide=()=>{tooltip.hidden=true;};
  const show=target=>{const item=snapshot().cashflow[Number(target.dataset.cashflowIndex)];if(!item)return;tooltip.querySelector("[data-tooltip-label]").textContent=item.label;tooltip.querySelector("[data-tooltip-income]").textContent=money(item.income);tooltip.querySelector("[data-tooltip-expense]").textContent=money(item.expense);tooltip.querySelector("[data-tooltip-balance]").textContent=money(item.balance);Object.entries(snapshot().cashflowVisible).forEach(([name,value])=>{const row=tooltip.querySelector(`[data-tooltip-row="${name}"]`);if(row)row.hidden=!value;});tooltip.hidden=false;const visualRect=visual.getBoundingClientRect(),targetRect=target.getBoundingClientRect(),half=tooltip.offsetWidth/2+8,center=targetRect.left+targetRect.width/2-visualRect.left;tooltip.style.left=`${Math.max(half,Math.min(visualRect.width-half,center))}px`;};
  visual.querySelectorAll("[data-cashflow-index]").forEach(target=>{target.addEventListener("mouseenter",()=>show(target));target.addEventListener("focus",()=>show(target));target.addEventListener("blur",hide);});visual.addEventListener("mouseleave",hide);
}

function openCategory(id=""){const item=snapshot().categories.find(x=>x.id===id);forms.category.reset();forms.category.elements.categoryId.value=id;forms.category.elements.version.value=item?.version||"";forms.category.elements.categoryType.disabled=Boolean(item);if(item){forms.category.elements.name.value=item.name;forms.category.elements.categoryType.value=item.categoryType;forms.category.elements.sortOrder.value=item.sortOrder;}dialogs.category.showModal();}
async function deleteCategory(id){const item=snapshot().categories.find(x=>x.id===id);if(!item||!confirm(`“${item.name}” silinsin mi? Kullanılmışsa pasife alınacaktır.`))return;await mutate(()=>container.finance.deleteCategory(id,item.version),"Kategori silindi veya geçmişi olduğu için pasife alındı","settings");}
async function activateCategory(id){const item=snapshot().categories.find(x=>x.id===id);await mutate(()=>container.finance.updateCategory(id,{isActive:true,version:item.version}),"Kategori etkinleştirildi","settings");}

function openAssetType(id=""){const item=snapshot().investmentTypes.find(x=>x.id===id);forms.assetType.reset();forms.assetType.elements.assetTypeId.value=id;forms.assetType.elements.version.value=item?.version||"";forms.assetType.elements.sortOrder.value=item?.sortOrder||0;if(item)forms.assetType.elements.name.value=item.name;dialogs.assetType.showModal();}
async function deleteAssetType(id){const item=snapshot().investmentTypes.find(x=>x.id===id);if(!item||!confirm(`“${item.name}” silinsin mi? Kullanılıyorsa pasife alınacaktır.`))return;await mutate(()=>container.finance.deleteAssetType(id,item.version),"Birikim türü güncellendi","settings");}
async function activateAssetType(id){const item=snapshot().investmentTypes.find(x=>x.id===id);await mutate(()=>container.finance.updateAssetType(id,{isActive:true,version:item.version}),"Birikim türü etkinleştirildi","settings");}

function openInstrument(id=""){const item=snapshot().instruments.find(x=>x.id===id);forms.instrument.reset();forms.instrument.elements.instrumentId.value=id;forms.instrument.elements.version.value=item?.version||"";forms.instrument.elements.assetTypeId.innerHTML=options(snapshot().investmentTypes.filter(x=>x.isActive),x=>x.name,"Tür seçin");if(item){forms.instrument.elements.name.value=item.name;forms.instrument.elements.symbol.value=item.symbol||"";forms.instrument.elements.assetTypeId.value=item.assetTypeId;}dialogs.instrument.showModal();}
async function deleteInstrument(id){const item=snapshot().instruments.find(x=>x.id===id);if(!item||!confirm(`“${item.name}” silinsin mi? Portföydeyse pasife alınacaktır.`))return;await mutate(()=>container.finance.deleteInstrument(id,item.version),"Yatırım aracı güncellendi","settings");}
function openPrice(id){const item=snapshot().instruments.find(x=>x.id===id);forms.price.reset();forms.price.elements.instrumentId.value=id;forms.price.elements.pricedAt.value=today();document.querySelector("#price-instrument-name").textContent=item?.name||"";dialogs.price.showModal();}

function openLot(id=""){const item=snapshot().lots.find(x=>x.id===id);forms.lot.reset();forms.lot.elements.lotId.value=id;forms.lot.elements.version.value=item?.version||"";forms.lot.elements.purchasedAt.value=item?String(item.purchasedAt).slice(0,10):today();forms.lot.elements.instrumentId.innerHTML=options(snapshot().instruments.filter(x=>x.isActive),x=>`${x.name}${x.symbol?` (${x.symbol})`:""}`,"Yatırım aracı seçin");forms.lot.elements.accountId.innerHTML=options(snapshot().accounts.filter(x=>!x.isArchived),x=>x.name,"Hesap ilişkilendirme");if(item){forms.lot.elements.instrumentId.value=item.instrumentId;forms.lot.elements.accountId.value=item.accountId||"";forms.lot.elements.quantity.value=item.quantity;forms.lot.elements.unitPrice.value=item.unitPrice;forms.lot.elements.notes.value=item.notes||"";}dialogs.lot.querySelector("h2").textContent=item?"Alımı düzenle":"Birikim alımı";dialogs.lot.showModal();}
async function deleteLot(id){const item=snapshot().lots.find(x=>x.id===id);if(!item||!confirm("Bu birikim alımı silinsin mi?"))return;await mutate(()=>container.finance.deleteLot(id,item.version),"Birikim alımı silindi","savings");}
function openSale(id=""){const state=snapshot(),item=state.sales.find(x=>x.id===id);forms.sale.reset();forms.sale.elements.saleId.value=id;forms.sale.elements.version.value=item?.version||"";forms.sale.elements.soldAt.value=item?String(item.soldAt).slice(0,10):today();const instruments=item?state.instruments.filter(x=>x.isActive||x.id===item.instrumentId):state.portfolio.map(x=>({...x,id:x.instrumentId}));forms.sale.elements.instrumentId.innerHTML=options(instruments,x=>`${x.name}${x.symbol?` (${x.symbol})`:""}${item?"":` · ${x.quantity} adet`}`,"Yatırım aracı seçin");forms.sale.elements.destinationAccountId.innerHTML=options(state.accounts.filter(x=>!x.isArchived||x.id===item?.destinationAccountId),x=>x.name,"Paranın geçtiği hesabı seçin");if(item){forms.sale.elements.instrumentId.value=item.instrumentId;forms.sale.elements.destinationAccountId.value=item.destinationAccountId;forms.sale.elements.quantity.value=item.quantity;forms.sale.elements.unitPrice.value=item.unitPrice;forms.sale.elements.notes.value=item.notes||"";}dialogs.sale.querySelector("h2").textContent=item?"Satışı düzenle":"Birikim satışı";dialogs.sale.querySelector('button[type="submit"]').textContent=item?"Değişiklikleri kaydet":"Satışı kaydet";dialogs.sale.showModal();}
async function deleteSale(id){const item=snapshot().sales.find(x=>x.id===id);if(!item||!confirm(`“${item.instrumentName}” satışı silinsin mi? Hesaba geçen ${money(item.proceeds)} ters kayıtla geri alınacaktır.`))return;await mutate(()=>container.finance.deleteSale(id,item.version),"Birikim satışı silindi ve hesap hareketi geri alındı","savings");}

function exportVisibleTransactions(){const ids=new Set([...document.querySelectorAll("#all-transactions .table-row[data-transaction-id]:not([hidden])")].map(x=>x.dataset.transactionId)),state=snapshot(),rows=state.transactions.filter(x=>ids.has(x.id));if(!rows.length){toast("Dışa aktarılacak kayıt yok");return;}const values=[["Tarih","Tür","Açıklama","Kaynak hesap","Hedef hesap","Kategori","Tutar","Yürüyen bakiye"],...(transactionFilters.from?[[transactionFilters.from,"devir","Başlangıç öncesi devir","","","",0,state.transactionOpeningBalance]]:[]),...rows.map(x=>[x.date,x.kind,x.description,state.accounts.find(a=>a.id===x.accountId)?.name||"",state.accounts.find(a=>a.id===x.targetAccountId)?.name||"",state.categories.find(c=>c.id===x.categoryId)?.name||"",x.balanceDelta,x.runningBalance])];const csv=values.map(row=>row.map(csvCell).join(";")).join("\r\n"),url=URL.createObjectURL(new Blob(["\uFEFF",csv],{type:"text/csv;charset=utf-8"})),link=document.createElement("a");link.href=url;link.download=`defterx-islemler-${today()}.csv`;link.click();URL.revokeObjectURL(url);toast(`${rows.length} işlem dışa aktarıldı`);}
function csvCell(value){let text=String(value??"");if(/^[=+\-@]/.test(text))text=`'${text}`;return `"${text.replaceAll('"','""')}"`;}
function toast(message,forceGlobal=false){const dialog=[...document.querySelectorAll("dialog[open]")].at(-1);if(dialog&&!forceGlobal){let element=dialog.querySelector(".dialog-feedback");if(!element){element=document.createElement("p");element.className="dialog-feedback";element.setAttribute("role","alert");dialog.querySelector(".dialog-actions")?.before(element);}element.textContent=message;return;}const element=document.querySelector("#toast");element.textContent=message;element.classList.add("visible");setTimeout(()=>element.classList.remove("visible"),3200);}
function errorMessage(error){const labels={INVALID_CREDENTIALS:"E-posta veya parola hatalı.",EMAIL_EXISTS:"Bu e-posta zaten kayıtlı.",NEGATIVE_BALANCE_NOT_ALLOWED:"Bu hesap eksi bakiyeye düşemez.",ACCOUNT_LIMIT_EXCEEDED:"Hesap limiti aşılıyor.",ACCOUNT_TYPE_BALANCE_CONFLICT:"Bakiyesi olan bu hesabın türü borç/varlık yönünü değiştiremez.",RECURRENCE_TOO_LONG:"Tek seferde en fazla 240 tekrar oluşturulabilir.",CATEGORY_INVALID:"Kategori artık kullanılamıyor; planı düzenleyip etkin bir kategori seçin.",INVESTMENT_QUANTITY_EXCEEDED:"Satış adedi eldeki birikim adedini aşıyor.",INVESTMENT_HISTORY_LOCKED:"Satış yapılmış bir yatırımın eski alım lotları değiştirilemez; düzeltme lotu ekleyin.",VERSION_CONFLICT:"Kayıt başka bir yerde değişti; sayfa yenilendi.",NETWORK_ERROR:"Canlı API'ye ulaşılamadı."};if(error?.code==="VALIDATION_ERROR"){const names={bookId:"Defter",instrumentId:"Yatırım aracı",destinationAccountId:"Hedef hesap",quantity:"Adet",unitPrice:"Fiyat",soldAt:"Tarih",clientOperationId:"İşlem kimliği"},fields=Object.entries(error.details?.fieldErrors||{}).filter(([,messages])=>messages?.length).map(([field])=>names[field]||field);if(fields.length)return `Geçersiz veya eksik alan: ${fields.join(", ")}.`;}return labels[error?.code]||error?.message||"İşlem tamamlanamadı";}

forms.transaction.querySelectorAll('input[name="kind"]').forEach(x=>x.addEventListener("change",fillTransactionOptions));forms.account.elements.allowNegativeBalance.addEventListener("change",updateAccountLimit);forms.account.elements.accountType.addEventListener("change",()=>{forms.account.elements.allowNegativeBalance.checked=forms.account.elements.accountType.value==="CREDIT_CARD";updateAccountLimit();});forms.scheduled.elements.kind.addEventListener("change",()=>fillScheduledOptions(forms.scheduled.elements.kind.value));forms.scheduled.elements.repeat.addEventListener("change",updateScheduledRepeat);forms.scheduled.elements.date.addEventListener("change",updateScheduledRepeat);
document.querySelectorAll("[data-close-dialog]").forEach(x=>x.addEventListener("click",()=>x.closest("dialog").close()));document.querySelectorAll("[data-open-entry]").forEach(x=>x.addEventListener("click",()=>openTransaction()));document.querySelector("#mobile-menu").addEventListener("click",()=>document.querySelector(".sidebar").classList.toggle("open"));document.querySelectorAll(".primary-nav a,.sidebar-footer a").forEach(x=>x.addEventListener("click",()=>document.querySelector(".sidebar").classList.remove("open")));
document.querySelectorAll("dialog").forEach(dialog=>dialog.addEventListener("close",()=>dialog.querySelector(".dialog-feedback")?.remove()));document.querySelector("#sidebar-logout").addEventListener("click",logout);

forms.transaction.addEventListener("submit",async event=>{event.preventDefault();const f=forms.transaction.elements,amount=decimal(f.amount.value);if(!amount){toast("Sıfırdan büyük bir tutar girin");return;}if(f.kind.value==="transfer"&&f.accountId.value===f.targetAccountId.value){toast("Kaynak ve hedef hesap farklı olmalı");return;}const payload={type:f.kind.value.toUpperCase(),title:f.description.value.trim(),amount,accountId:f.accountId.value,transactionDate:isoAtNoon(f.date.value),...(f.kind.value==="transfer"?{targetAccountId:f.targetAccountId.value}:{categoryId:f.categoryId.value})};const id=f.transactionId.value,ok=await mutate(()=>id?container.finance.correctTransaction(id,payload):container.finance.createTransaction(payload),id?"İşlem düzeltildi":"İşlem kaydedildi","transactions");if(ok)dialogs.transaction.close();});
forms.account.addEventListener("submit",async event=>{event.preventDefault();const f=forms.account.elements,id=f.accountId.value,limit=f.creditLimit.value.trim()?decimal(f.creditLimit.value):null,payload=id?{name:f.name.value.trim(),accountType:f.accountType.value,allowNegativeBalance:f.allowNegativeBalance.checked,creditLimit:limit,version:Number(f.version.value)}:{name:f.name.value.trim(),accountType:f.accountType.value,allowNegativeBalance:f.allowNegativeBalance.checked,creditLimit:limit,openingBalance:String(Math.max(0,parseAmount(f.openingBalance.value))),sortOrder:0,isArchived:false};const ok=await mutate(()=>id?container.finance.updateAccount(id,payload):container.finance.createAccount(payload),id?"Hesap güncellendi":"Hesap eklendi","accounts");if(ok)dialogs.account.close();});
forms.scheduled.addEventListener("submit",async event=>{event.preventDefault();const f=forms.scheduled.elements,amount=decimal(f.amount.value);if(!amount){toast("Sıfırdan büyük bir tutar girin");return;}const transfer=f.kind.value==="transfer",base={transactionType:f.kind.value.toUpperCase(),title:f.title.value.trim(),amount,accountId:f.accountId.value,scheduledAt:isoAtNoon(f.date.value),targetAccountId:transfer?f.targetAccountId.value:null,categoryId:transfer?null:f.categoryId.value},id=f.scheduledId.value,payload=id?{...base,version:Number(f.version.value)}:{...base,...(f.repeat.value!=="NONE"?{recurrence:{frequency:f.repeat.value,interval:1,until:isoAtNoon(f.repeatUntil.value)}}:{})},ok=await mutate(()=>id?container.finance.updateScheduled(id,payload):container.finance.createScheduled(payload),id?"Plan güncellendi":"Planlı işlem eklendi","upcoming");if(ok)dialogs.scheduled.close();});
forms.category.addEventListener("submit",async event=>{event.preventDefault();const f=forms.category.elements,id=f.categoryId.value,payload=id?{name:f.name.value.trim(),sortOrder:Number(f.sortOrder.value)||0,version:Number(f.version.value)}:{name:f.name.value.trim(),categoryType:f.categoryType.value,sortOrder:Number(f.sortOrder.value)||0},ok=await mutate(()=>id?container.finance.updateCategory(id,payload):container.finance.createCategory(payload),id?"Kategori güncellendi":"Kategori eklendi","settings");if(ok)dialogs.category.close();});
forms.assetType.addEventListener("submit",async event=>{event.preventDefault();const f=forms.assetType.elements,id=f.assetTypeId.value,payload=id?{name:f.name.value.trim(),sortOrder:Number(f.sortOrder.value)||0,version:Number(f.version.value)}:{name:f.name.value.trim(),sortOrder:Number(f.sortOrder.value)||0},ok=await mutate(()=>id?container.finance.updateAssetType(id,payload):container.finance.createAssetType(payload),id?"Tür güncellendi":"Tür eklendi","settings");if(ok)dialogs.assetType.close();});
forms.instrument.addEventListener("submit",async event=>{event.preventDefault();const f=forms.instrument.elements,id=f.instrumentId.value,payload=id?{assetTypeId:f.assetTypeId.value,name:f.name.value.trim(),symbol:f.symbol.value.trim()||null,version:Number(f.version.value)}:{assetTypeId:f.assetTypeId.value,name:f.name.value.trim(),symbol:f.symbol.value.trim()||null},ok=await mutate(()=>id?container.finance.updateInstrument(id,payload):container.finance.createInstrument(payload),id?"Yatırım aracı güncellendi":"Yatırım aracı eklendi","settings");if(ok)dialogs.instrument.close();});
forms.lot.addEventListener("submit",async event=>{event.preventDefault();const f=forms.lot.elements,id=f.lotId.value,quantity=decimal(f.quantity.value),unitPrice=decimal(f.unitPrice.value);if(!quantity||!unitPrice){toast("Adet ve alış fiyatı sıfırdan büyük olmalı");return;}const base={instrumentId:f.instrumentId.value,accountId:f.accountId.value||null,quantity,unitPrice,purchasedAt:isoAtNoon(f.purchasedAt.value),notes:f.notes.value.trim()||null},payload=id?{...base,version:Number(f.version.value)}:base,ok=await mutate(()=>id?container.finance.updateLot(id,payload):container.finance.createLot(payload),id?"Birikim alımı güncellendi":"Birikim alımı eklendi","savings");if(ok)dialogs.lot.close();});
forms.sale.addEventListener("submit",async event=>{event.preventDefault();const f=forms.sale.elements,id=f.saleId.value,quantity=decimal(f.quantity.value),unitPrice=decimal(f.unitPrice.value);if(!quantity||!unitPrice){toast("Satış adedi ve fiyatı sıfırdan büyük olmalı");return;}const base={instrumentId:f.instrumentId.value,destinationAccountId:f.destinationAccountId.value,quantity,unitPrice,soldAt:isoAtNoon(f.soldAt.value),notes:f.notes.value.trim()||null},payload=id?{...base,version:Number(f.version.value)}:base,ok=await mutate(()=>id?container.finance.updateSale(id,payload):container.finance.createSale(payload),id?"Birikim satışı ve bağlı hesap hareketi güncellendi":"Birikim satışı kaydedildi ve bedel seçilen hesaba aktarıldı","savings");if(ok)dialogs.sale.close();});
forms.price.addEventListener("submit",async event=>{event.preventDefault();const f=forms.price.elements,price=decimal(f.price.value);if(!price){toast("Sıfırdan büyük bir fiyat girin");return;}const ok=await mutate(()=>container.finance.setPrice(f.instrumentId.value,{price,pricedAt:isoAtNoon(f.pricedAt.value)}),"Son fiyat kaydedildi","settings");if(ok)dialogs.price.close();});

document.querySelectorAll("[data-auth-tab]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-auth-tab]").forEach(x=>x.classList.toggle("active",x===button));document.querySelector("#login-form").hidden=button.dataset.authTab!=="login";document.querySelector("#register-form").hidden=button.dataset.authTab!=="register";document.querySelector("#auth-error").textContent="";}));
document.querySelector("#login-form").addEventListener("submit",event=>authSubmit(event,"login"));document.querySelector("#register-form").addEventListener("submit",event=>authSubmit(event,"register"));
async function authSubmit(event,mode){event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form)),button=form.querySelector("button[type=submit]");button.disabled=true;document.querySelector("#auth-error").textContent="";try{await container.apiClient[mode](data);await container.finance.initialize();ready=true;apiStatus=await container.apiClient.health();showApp();render("dashboard");}catch(error){document.querySelector("#auth-error").textContent=errorMessage(error);}finally{button.disabled=false;}}
async function logout(){await container.apiClient.logout();showAuth();}
document.querySelector("#sync-button").addEventListener("click",async()=>{apiStatus=await container.apiClient.health();await mutate(()=>container.finance.refresh(),apiStatus.online?"Canlı veriler yenilendi":errorMessage({code:"NETWORK_ERROR"}));});

hydrateIcons();new Router(render).start();bootstrap();
