import Foundation

@MainActor final class TransactionEntryViewModel:ObservableObject{
 @Published var type:TransactionType;@Published var amount="";@Published var accountId:UUID?;@Published var targetAccountId:UUID?;@Published var categoryId:UUID?;@Published var contactId:UUID?;@Published var date=Date();@Published var title="";@Published var note="";@Published var hasDueDate=false;@Published var dueDate=Date();@Published var accounts:[Account]=[];@Published var categories:[Category]=[];@Published var contacts:[Contact]=[];@Published var error:String?;@Published var saved=false
 private let container:AppContainer;private let book:Book
 init(type:TransactionType,book:Book,container:AppContainer){self.type=type;self.book=book;self.container=container}
 func load()async{async let a=container.accounts.list(bookId:book.id);async let c=container.categories.list(bookId:book.id);async let p=container.contacts.list(bookId:book.id);do{accounts=try await a;categories=try await c;contacts=try await p;accountId=accounts.first?.id}catch{self.error=error.localizedDescription}}
 var visibleCategories:[Category]{let expected:CategoryType=[.income,.sale].contains(type) ? .income:.expense;return categories.filter{$0.categoryType==expected}}
 var needsCategory:Bool{[.income,.expense,.sale,.purchase].contains(type)};var needsTarget:Bool{type == .transfer};var needsContact:Bool{[.collection,.payment,.sale,.purchase].contains(type)}
 func save()async{do{guard let accountId else{throw EntryError.missingAccount};let value=try Money(amount);guard value.decimal>0 else{throw EntryError.invalidAmount};if needsCategory&&categoryId==nil{throw EntryError.missingCategory};if needsTarget&&targetAccountId==nil{throw EntryError.missingTarget};if needsContact&&contactId==nil{throw EntryError.missingContact};let transaction=FinanceTransaction(id:UUID(),bookId:book.id,type:type,title:title.isEmpty ? defaultTitle:title,amount:value,currencyCode:book.baseCurrency,accountId:accountId,targetAccountId:targetAccountId,categoryId:categoryId,contactId:contactId,transactionDate:date,dueDate:hasDueDate ? dueDate:nil,details:note.isEmpty ? nil:note,clientOperationId:UUID(),serverVersion:nil,syncState:.pending);try await container.transactions.createOffline(transaction);saved=true;await container.sync.sync(bookId:book.id)}catch{self.error=error.localizedDescription}}
 private var defaultTitle:String{switch type{case.income:"Gelir";case.expense:"Gider";case.transfer:"Transfer";case.collection:"Tahsilat";case.payment:"Ödeme";default:"İşlem"}}
}
enum EntryError:LocalizedError{case missingAccount,invalidAmount,missingCategory,missingTarget,missingContact;var errorDescription:String?{switch self{case.missingAccount:"Hesap seçin";case.invalidAmount:"Geçerli bir tutar girin";case.missingCategory:"Kategori seçin";case.missingTarget:"Hedef hesap seçin";case.missingContact:"Cari seçin"}}}
