import { afterAll,beforeAll,describe,expect,it } from 'vitest';import pg from 'pg';import{readdir,readFile}from'node:fs/promises';import{join}from'node:path';import{createTransaction,reverseTransaction}from'../../src/modules/transactions/transaction.service';import{requireBookRole}from'../../src/middleware/book-access';
const connectionString=process.env.TEST_DATABASE_URL;const suite=describe.skipIf(!connectionString);let admin:pg.Client,pool:pg.Pool,schema:string,userId:string,otherId:string,viewerId:string,bookId:string,cashId:string,bankId:string,incomeCategoryId:string,expenseCategoryId:string,deletedId:string;
suite('PostgreSQL ledger integration',()=>{beforeAll(async()=>{schema=`test_${crypto.randomUUID().replaceAll('-','')}`;admin=new pg.Client({connectionString});await admin.connect();await admin.query(`CREATE SCHEMA ${schema}`);await admin.query(`SET search_path TO ${schema},public`);for(const file of(await readdir(join(process.cwd(),'packages/database/migrations'))).filter(f=>f.endsWith('.sql')).sort())await admin.query(await readFile(join(process.cwd(),'packages/database/migrations',file),'utf8'));const users=await admin.query(`INSERT INTO users(email,display_name,status) VALUES('owner@example.com','Owner','ACTIVE'),('other@example.com','Other','ACTIVE'),('viewer@example.com','Viewer','ACTIVE') RETURNING id`);[userId,otherId,viewerId]=users.rows.map(r=>r.id);const book=await admin.query(`INSERT INTO books(name,book_type,base_currency,owner_user_id)VALUES('Test','PERSONAL','TRY',$1)RETURNING id`,[userId]);bookId=book.rows[0].id;await admin.query(`INSERT INTO book_members(book_id,user_id,role,status)VALUES($1,$2,'OWNER','ACTIVE'),($1,$3,'VIEWER','ACTIVE')`,[bookId,userId,viewerId]);const accounts=await admin.query(`INSERT INTO accounts(book_id,name,account_type,normal_balance,currency_code,is_system)VALUES($1,'Cash','CASH','DEBIT','TRY',false),($1,'Bank','BANK','DEBIT','TRY',false),($1,'Income','SYSTEM_INCOME','CREDIT','TRY',true),($1,'Expense','SYSTEM_EXPENSE','DEBIT','TRY',true),($1,'Deleted','CASH','DEBIT','TRY',false) RETURNING id`,[bookId]);[cashId,bankId]=accounts.rows;cashId=accounts.rows[0].id;bankId=accounts.rows[1].id;deletedId=accounts.rows[4].id;await admin.query(`UPDATE accounts SET deleted_at=now() WHERE id=$1`,[deletedId]);const categories=await admin.query(`INSERT INTO categories(book_id,name,category_type,system_account_id)VALUES($1,'Sales','INCOME',$2),($1,'Market','EXPENSE',$3)RETURNING id`,[bookId,accounts.rows[2].id,accounts.rows[3].id]);incomeCategoryId=categories.rows[0].id;expenseCategoryId=categories.rows[1].id;await admin.end();pool=new pg.Pool({connectionString,options:`-c search_path=${schema},public`});},120000);
afterAll(async()=>{if(pool)await pool.end();if(connectionString&&schema){const cleanup=new pg.Client({connectionString});await cleanup.connect();await cleanup.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);await cleanup.end();}},120000);
const input=(overrides:Record<string,unknown>={})=>({bookId,type:'INCOME' as const,title:'Income',amount:'1000.000001',currencyCode:'TRY',accountId:cashId,categoryId:incomeCategoryId,transactionDate:new Date().toISOString(),clientOperationId:crypto.randomUUID(),...overrides});
it('deduplicates an offline retry by client operation and idempotency key',async()=>{const payload=input(),first=await createTransaction(pool,userId,payload,'offline-op-1'),second=await createTransaction(pool,userId,payload,'offline-op-1');expect(second.id).toBe(first.id);const count=await pool.query(`SELECT count(*)::int count FROM transactions WHERE client_operation_id=$1`,[payload.clientOperationId]);expect(count.rows[0].count).toBe(1);});
it('posts income, expense, transfer and reconstructs balances',async()=>{await createTransaction(pool,userId,input(),'income');await createTransaction(pool,userId,input({type:'EXPENSE',title:'Market',amount:'200',categoryId:expenseCategoryId}),'expense');await createTransaction(pool,userId,input({type:'TRANSFER',title:'Move',amount:'300',categoryId:undefined,targetAccountId:bankId}),'transfer');const unbalanced=await pool.query(`SELECT transaction_id FROM transaction_entries GROUP BY transaction_id HAVING SUM(base_amount)FILTER(WHERE direction='DEBIT')<>SUM(base_amount)FILTER(WHERE direction='CREDIT')`);expect(unbalanced.rowCount).toBe(0);const balance=await pool.query(`SELECT COALESCE(SUM(CASE WHEN direction='DEBIT'THEN base_amount ELSE-base_amount END),0)::text value FROM transaction_entries WHERE account_id=$1`,[cashId]);expect(balance.rows[0].value).toMatch(/^1500\.000002/);});
it('reversal preserves immutable history and nets the balance',async()=>{const original=await createTransaction(pool,userId,input({amount:'42'}),'reverse-original');await reverseTransaction(pool,userId,bookId,original.id,crypto.randomUUID(),'mistake');const rows=await pool.query(`SELECT status FROM transactions WHERE id=$1`,[original.id]);expect(rows.rows[0].status).toBe('REVERSED');const net=await pool.query(`SELECT SUM(CASE WHEN e.direction='DEBIT'THEN e.base_amount ELSE-e.base_amount END)::text value FROM transaction_entries e JOIN transactions t ON t.id=e.transaction_id WHERE e.account_id=$1 AND(t.id=$2 OR t.reverses_transaction_id=$2)`,[cashId,original.id]);expect(net.rows[0].value).toMatch(/^0\.0/);});
it('denies unauthorized and viewer mutations',async()=>{await expect(requireBookRole(pool,bookId,otherId,'VIEWER')).rejects.toMatchObject({code:'BOOK_ACCESS_DENIED'});await expect(requireBookRole(pool,bookId,viewerId,'EDITOR')).rejects.toMatchObject({code:'INSUFFICIENT_ROLE'});});
it('rejects a deleted account',async()=>{await expect(createTransaction(pool,userId,input({accountId:deletedId}),'deleted-account')).rejects.toMatchObject({code:'ACCOUNT_UNAVAILABLE'});});
});

