import { money,dateText } from "../../Core/Formatting/formatters.js";
import { escapeHtml } from "../../Core/Security/html.js";

export function SettingsView(state,context){const online=Boolean(context.apiStatus?.online);return `<section class="page-section settings-stack">
  <div class="settings-grid"><article class="panel settings-card"><h2>Canlı ortam</h2><div class="settings-row"><span>Web uygulaması</span><b>Cloudflare Workers</b></div><div class="settings-row"><span>API ve Neon</span><b class="${online?"income":"expense"}">${online?"Bağlı":"Bağlantı hatası"}</b></div><div class="settings-row"><span>Aktif defter</span><b>${escapeHtml(state.book?.name||"—")}</b></div><div class="settings-row"><span>API adresi</span><code>${escapeHtml(context.configuration.apiBaseUrl||"Tanımsız")}</code></div><p class="connection-detail">${escapeHtml(context.apiStatus?.reason||"")}</p><button class="secondary-button" id="logout-button">Oturumu kapat</button></article>
  <article class="panel settings-card"><h2>Veri ilkeleri</h2><p>Tüm finansal kayıtlar canlı API üzerinden Neon PostgreSQL’de tutulur. Tarayıcıda demo bakiye veya demo işlem saklanmaz.</p><div class="settings-row"><span>Para birimi</span><b>${escapeHtml(state.book?.baseCurrency||"TRY")}</b></div><div class="settings-row"><span>Hesap sahibi</span><b>${escapeHtml(state.user?.displayName||state.user?.email||"—")}</b></div></article></div>
  <article class="panel settings-card"><header class="panel-head"><div><h2>Kategoriler</h2><p>Kullanılmış kategori silinmek yerine pasife alınır; geçmiş raporlarda korunur.</p></div><button class="secondary-button" id="open-category-dialog">+ Kategori</button></header><div class="management-list">${state.categories.map(item=>`<div><span><b>${escapeHtml(item.name)}</b><small>${item.categoryType==="INCOME"?"Gelir":"Gider"}${item.isActive?"":" · Pasif"}</small></span><span class="row-actions"><button data-edit-category="${item.id}">Düzenle</button>${item.isActive?`<button class="danger-link" data-delete-category="${item.id}">Sil / pasif al</button>`:`<button data-activate-category="${item.id}">Etkinleştir</button>`}</span></div>`).join("")}</div></article>
  <div class="settings-grid"><article class="panel settings-card"><header class="panel-head"><div><h2>Birikim türleri</h2><p>Hisse, fon, ETF ve özel türler</p></div><button class="secondary-button" id="open-asset-type-dialog">+ Tür</button></header><div class="management-list compact-list">${state.investmentTypes.map(item=>`<div><span><b>${escapeHtml(item.name)}</b><small>${item.isActive?"Aktif":"Pasif"}</small></span><span class="row-actions"><button data-edit-asset-type="${item.id}">Düzenle</button>${item.isActive?`<button class="danger-link" data-delete-asset-type="${item.id}">Sil / pasif al</button>`:`<button data-activate-asset-type="${item.id}">Etkinleştir</button>`}</span></div>`).join("")}</div></article>
  <article class="panel settings-card"><header class="panel-head"><div><h2>Yatırım araçları ve fiyatlar</h2><p>Takip ettiğiniz menkul kıymetler</p></div><button class="secondary-button" id="open-instrument-dialog">+ Araç</button></header><div class="management-list compact-list">${state.instruments.map(item=>`<div><span><b>${escapeHtml(item.name)} ${item.symbol?`(${escapeHtml(item.symbol)})`:""}</b><small>${escapeHtml(item.assetTypeName)} · ${item.latestPrice?`${money(item.latestPrice)} · ${dateText(item.latestPriceAt)}`:"Fiyat yok"}${item.isActive?"":" · Pasif"}</small></span><span class="row-actions"><button data-price-instrument="${item.id}">Fiyat gir</button><button data-edit-instrument="${item.id}">Düzenle</button>${item.isActive?`<button class="danger-link" data-delete-instrument="${item.id}">Sil</button>`:""}</span></div>`).join("")||`<div class="empty-state">Henüz yatırım aracı tanımlanmadı.</div>`}</div></article></div>
  </section>`;}
