import { dateText,money } from "../../Core/Formatting/formatters.js";
import { escapeHtml } from "../../Core/Security/html.js";

const labels={income:"Gelir",expense:"Gider",transfer:"Transfer",opening_balance:"Açılış bakiyesi",adjustment:"Düzeltme"};

export function TransactionsView(state,{transactionFilters={}}={}){
  const accounts=state.accounts||[],selected=new Set(transactionFilters.accountIds||[]),allSelected=accounts.length>0&&accounts.every(item=>selected.has(item.id));
  const ordered=transactionFilters.from?[...state.transactions].sort((a,b)=>a.date.localeCompare(b.date)||Number(a.transactionNo)-Number(b.transactionNo)):state.transactions;
  const accountLabel=allSelected?"Tüm hesaplar":`${selected.size} hesap`;
  const carry=transactionFilters.from?carryRow(state.transactionOpeningBalance,transactionFilters.from):"";
  return `<section class="page-section"><div class="filter-bar transaction-filters"><div class="search-field">⌕ <input id="transaction-search" value="${escapeHtml(transactionFilters.search||"")}" placeholder="İşlemlerde ara"></div><select id="transaction-kind-filter"><option value="">Tüm türler</option>${["income","expense","transfer"].map(x=>`<option value="${x}"${transactionFilters.kind===x?" selected":""}>${labels[x]}</option>`).join("")}</select>${accountFilter(accounts,selected,allSelected,accountLabel)}<label class="date-filter"><span>Başlangıç</span><input id="transaction-from" type="date" value="${escapeHtml(transactionFilters.from||"")}"></label><label class="date-filter"><span>Bitiş</span><input id="transaction-to" type="date" value="${escapeHtml(transactionFilters.to||"")}"></label><button class="secondary-button compact-button" id="clear-transaction-filters" type="button">Temizle</button></div><article class="panel transaction-panel"><header class="panel-head"><div><h2>İşlem defteri</h2><p id="transaction-result-count">${state.transactions.length} kayıt bulundu</p></div><button class="secondary-button" id="export-transactions" type="button">Dışa aktar (.csv)</button></header><div class="transaction-table expanded transaction-ledger" id="all-transactions"><div class="table-head"><span>İşlem</span><span>Kategori</span><span>Hesap</span><span>Tarih</span><span>Tutar</span><span>Yürüyen bakiye</span><span>İşlemler</span></div>${carry}${ordered.map(item=>row(item,state)).join("")}</div><div class="empty-state" id="transaction-empty"${state.transactions.length?" hidden":""}>Kayıt bulunamadı.</div></article></section>`;
}

function accountFilter(accounts,selected,allSelected,label){return `<details class="multi-select-filter" id="transaction-account-filter"><summary><small>Hesaplar</small><span>${escapeHtml(label)}</span></summary><div class="multi-select-menu"><label class="multi-select-all"><input type="checkbox" data-transaction-account-all ${allSelected?"checked":""}><span>Tüm hesaplar</span></label>${accounts.map(item=>`<label><input type="checkbox" data-transaction-account="${item.id}" ${selected.has(item.id)?"checked":""}><span>${escapeHtml(item.name)}${item.isArchived?" · Arşivli":""}</span></label>`).join("")||`<small>Tanımlı hesap yok.</small>`}</div></details>`;}
function carryRow(balance,date){return `<div class="table-row carry-row" data-carry-row><span class="transaction-name"><i style="--dot:#66829f">↪</i><b>Devir</b></span><span>Başlangıç öncesi</span><span>Seçili hesaplar</span><span>${dateText(date)}</span><strong>—</strong><strong>${money(balance)}</strong><span><small>Devir bakiyesi</small></span></div>`;}
function impactMoney(value){const amount=Number(value)||0;return `${amount>0?"+":amount<0?"−":""}${money(Math.abs(amount))}`;}
function row(item,state){const c=state.categories.find(x=>x.id===item.categoryId),a=state.accounts.find(x=>x.id===item.accountId),t=state.accounts.find(x=>x.id===item.targetAccountId);const category=item.kind==="transfer"?"Hesaplar arası":c?.name||item.categoryName||(item.kind==="opening_balance"?"Açılış bakiyesi":item.kind==="adjustment"?"Sistem düzeltmesi":"—"),account=item.kind==="transfer"?`${a?.name||item.accountName||"Hesap"} → ${t?.name||item.targetAccountName||"Hedef"}`:a?.name||item.accountName||"—";const search=`${item.description} ${category} ${account} ${labels[item.kind]||""}`.toLocaleLowerCase("tr-TR"),editable=["income","expense","transfer"].includes(item.kind),actions=editable?`<button type="button" data-edit-transaction="${item.id}">Düzelt</button><button type="button" class="danger-link" data-delete-transaction="${item.id}">Sil</button>`:`<small>Sistem kaydı</small>`;return `<div class="table-row" data-transaction-id="${item.id}" data-kind="${item.kind}" data-date="${item.date}" data-search="${escapeHtml(search)}"><span class="transaction-name"><i style="--dot:#287b60">${item.kind==="income"?"↙":item.kind==="transfer"?"⇄":item.kind==="opening_balance"?"↪":"↗"}</i><b>${escapeHtml(item.description)}</b></span><span>${escapeHtml(category)}</span><span>${escapeHtml(account)}</span><span>${dateText(item.date)}</span><strong class="${item.balanceDelta<0?"expense":item.balanceDelta>0?"income":"transfer"}">${impactMoney(item.balanceDelta)}</strong><strong class="running-balance">${money(item.runningBalance)}</strong><span class="row-actions">${actions}</span></div>`;}
